require "bundler/gem_tasks"

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = ['test/darius/article_manager/*_test.rb']
end

desc "Run tests"
task :default => :test
