require "bundler/gem_tasks"

require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << 'test'
  t.test_files = ['test/darius/article_manager/*_test.rb']
end

#desc "Run tests"
#task :default => :test

namespace :darius do

  #desc "Darius Thrift Server"
  task :server, :config_file do |t, args|
    require 'darius/article_manager/utils/configuration_util'
    require 'darius/article_manager/article_manager_server'

    config = ColdBlossom::Darius::ArticleManager::Utils::ConfigurationUtil.load_config_from_file args[:config_file]
    server = ColdBlossom::Darius::ArticleManager::ArticleManagerServer.new config
    server.start
  end
end

