#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require_relative 'archive_file_format_types'

module ColdBlossom
  module Darius
    module Archive
      MAGIC = %q"ARH1"

      VERSION = 1

      FORMAT_CODE_TEXT = 0

      FORMAT_CODE_DEFLATE = 1

    end
  end
end
