#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'

module ColdBlossom
  module Darius
    module Archive
      class IndexEntry
        include ::Thrift::Struct, ::Thrift::Struct_Union
        KEY = 1
        OFFSET = 2
        LENGTH = 3

        FIELDS = {
          KEY => {:type => ::Thrift::Types::STRING, :name => 'key'},
          OFFSET => {:type => ::Thrift::Types::I32, :name => 'offset'},
          LENGTH => {:type => ::Thrift::Types::I32, :name => 'length'}
        }

        def struct_fields; FIELDS; end

        def validate
        end

        ::Thrift::Struct.generate_accessors self
      end

      class IndexSegment
        include ::Thrift::Struct, ::Thrift::Struct_Union
        NAME = 1
        INDEX_ENTRIES = 2

        FIELDS = {
          NAME => {:type => ::Thrift::Types::STRING, :name => 'name'},
          INDEX_ENTRIES => {:type => ::Thrift::Types::LIST, :name => 'index_entries', :element => {:type => ::Thrift::Types::STRUCT, :class => ::ColdBlossom::Darius::Archive::IndexEntry}}
        }

        def struct_fields; FIELDS; end

        def validate
        end

        ::Thrift::Struct.generate_accessors self
      end

      class ContentMetadata
        include ::Thrift::Struct, ::Thrift::Struct_Union
        KEY = 1
        VALUE = 2

        FIELDS = {
          KEY => {:type => ::Thrift::Types::STRING, :name => 'key'},
          VALUE => {:type => ::Thrift::Types::STRING, :name => 'value'}
        }

        def struct_fields; FIELDS; end

        def validate
        end

        ::Thrift::Struct.generate_accessors self
      end

      class ContentSegment
        include ::Thrift::Struct, ::Thrift::Struct_Union
        FORMAT_CODE = 1
        MATADATA = 2
        CONTENT = 3

        FIELDS = {
          FORMAT_CODE => {:type => ::Thrift::Types::I32, :name => 'format_code'},
          MATADATA => {:type => ::Thrift::Types::LIST, :name => 'matadata', :element => {:type => ::Thrift::Types::STRUCT, :class => ::ColdBlossom::Darius::Archive::ContentMetadata}},
          CONTENT => {:type => ::Thrift::Types::STRING, :name => 'content', :binary => true}
        }

        def struct_fields; FIELDS; end

        def validate
        end

        ::Thrift::Struct.generate_accessors self
      end

      class ArchiveFileFormat
        include ::Thrift::Struct, ::Thrift::Struct_Union
        MAGIC = 1
        VERSION = 2
        INDEX_SEGMENTS = 3
        CONTENT_SEGMENTS = 4

        FIELDS = {
          MAGIC => {:type => ::Thrift::Types::STRING, :name => 'magic', :binary => true},
          VERSION => {:type => ::Thrift::Types::I32, :name => 'version'},
          INDEX_SEGMENTS => {:type => ::Thrift::Types::LIST, :name => 'index_segments', :element => {:type => ::Thrift::Types::STRUCT, :class => ::ColdBlossom::Darius::Archive::IndexSegment}},
          CONTENT_SEGMENTS => {:type => ::Thrift::Types::LIST, :name => 'content_segments', :element => {:type => ::Thrift::Types::STRUCT, :class => ::ColdBlossom::Darius::Archive::ContentSegment}}
        }

        def struct_fields; FIELDS; end

        def validate
        end

        ::Thrift::Struct.generate_accessors self
      end

    end
  end
end
