#
# Autogenerated by Thrift Compiler (0.9.1)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

require 'thrift'
require 'article_manager_types'

module ColdBlossom
  module Darius
    MAJOR_VERSION = 1

    MINOR_VERSION = 0

    PATCH_VERSION = 0

  end
end
